name: securx
description: "A robust mobile security package designed to enhance application resilience against various threats. This package includes features for device integrity checks, secure communication, mobile privacy, and fraud prevention."
version: 0.0.1
homepage: https://github.com/Rgada28/securx
repository: https://github.com/Rgada28/securx
issue_tracker: https://github.com/Rgada28/securx/issues
license: BSD-3-Clause

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  plugin:
    platforms:
      android:
        package: com.security.securx.securx
        pluginClass: SecurxPlugin
      ios:
        pluginClass: SecurxPlugin
