name: app_guard
description: "A Flutter plugin for comprehensive device and OS integrity checks to enhance mobile app security."
version: 0.0.1
homepage: "https://github.com/Rgada28/app_guard"

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  connectivity_plus: ^6.1.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter:
  plugin:
    platforms:
      android:
        package: com.security.app_guard
        pluginClass: AppGuard
      ios:
        pluginClass: AppGuard
